# generated by datamodel-codegen:
#   filename:  tea-log.json
#   timestamp: 2023-10-05T20:31:48+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Supplements(BaseModel):
    butterfly_pea_flower: Optional[float] = None
    ginger: Optional[float] = None
    shatavari: Optional[float] = None
    rose_water: Optional[float] = None
    lemon: Optional[float] = None
    matcha: Optional[float] = None
    vitamin_b_complex: Optional[float] = None
    spice_mix: Optional[float] = None
    ashwagandha: Optional[float] = None
    saffron: Optional[float] = None
    omega_3: Optional[float] = None
    coffee: Optional[float] = None
    moringa: Optional[float] = None
    tulsi: Optional[float] = None
    licorice: Optional[float] = None
    turmeric: Optional[float] = None
    nuun_energy: Optional[float] = None
    hibiscus_flower: Optional[float] = None
    black_tea: Optional[float] = None
    sukku_malli_coffee: Optional[float] = None
    lemon_balm: Optional[float] = None
    arjuna_bark: Optional[float] = None
    st_johns_wart: Optional[float] = None
    cardamom: Optional[float] = None
    valerian_root: Optional[float] = None
    spearmint: Optional[float] = None
    cinnamon: Optional[float] = None


class Medium(BaseModel):
    type: str
    temperature: str


class Stack(BaseModel):
    supplements: Supplements
    medium: Medium


class Scores(BaseModel):
    mood: float
    depression: float
    focus: float
    anxiety: float
    energy: Optional[float] = None


class ModelItem(BaseModel):
    stack: Stack
    scores: Scores
    date_time: str


class Model(BaseModel):
    __root__: List[ModelItem]
